### PR TITLE
Update LaradropController.php

### PR DESCRIPTION
**Pull request by phpner**
i think you should do something like this

### CODE REVIEW

**Comment by jasekz** [comment]
Hi Alex,
Thanks for submitting the pull request.  After reviewing this and doing a bit of research, I came to the conclusion that using mime types in lieu of file types does not necessarily improve anything because mime types coming from a browser are no more reliable than extension types.  Were you running into issues with this method of file type sniffing?  

Thanks,
Zig

**Comment by phpner** [comment]
I'll be know about reliability ! But only this way work very well if I leave everything as  it is . The code is not  always make mini images ! I'm not strong in php  but i wanna be ! ))))And i'm not saying about russian letters  in  name of files ! because it's not work as well (((

**Comment by jasekz** [comment]
Does it work as expected when you use mime types to validate the files?

**Comment by phpner** [comment]
Yes it does !!! Work very well ! I have tried more than twice time with clear setup laravel ! And only the change helped me .

**Comment by jasekz** [comment]
Ok, thanks Alex.  I merged your changes in.

**Pull request merged**
